version: '3.5'

services:
  issuer:
    build:
      context: .
      dockerfile: Dockerfile.acapy
    ports:
      - 8080:8080
      - 8000:8000
    env_file:
      - .env
      - env.common
      - env.issuer
    entrypoint: [ "aca-py", "start", "--admin", "0.0.0.0", "8080", "--inbound-transport", "http", "0.0.0.0", "8000"]
  holder:
    build:
      context: .
      dockerfile: Dockerfile.acapy
    ports:
      - 7070:7070
      - 7000:7000
    env_file:
      - .env
      - env.common
      - env.holder
    entrypoint: [ "aca-py", "start", "--admin", "0.0.0.0", "7070", "--inbound-transport", "http", "0.0.0.0", "7000"]
  verifier:
    build:
      context: .
      dockerfile: Dockerfile.acapy
    ports:
      - 9090:9090
      - 9000:9000
    env_file:
      - .env
      - env.common
      - env.verifier
    entrypoint: [ "aca-py", "start", "--admin", "0.0.0.0", "9090", "--inbound-transport", "http", "0.0.0.0", "9000"]
