version: '3.5'

services:
  issuer:
    build:
      context: .
      dockerfile: Dockerfile.acapy
    ports:
      - 8080:8080
      - 8000:8000
    env_file:
      - .env
      - common.env
      - issuer.env
    entrypoint: [ "aca-py", "start", "--admin", "0.0.0.0", "8080", "--inbound-transport", "http", "0.0.0.0", "8000"]
  holder:
    build:
      context: .
      dockerfile: Dockerfile.acapy
    ports:
      - 7070:7070
      - 7000:7000
    env_file:
      - common.env
      - holder.env
    entrypoint: [ "aca-py", "start", "--admin", "0.0.0.0", "7070", "--inbound-transport", "http", "0.0.0.0", "7000"]


