version: '3.5'

services:
  # postgres:
  #   image: postgres:10
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=mysecretpassword
  issuer:
    build:
      context: .
      dockerfile: Dockerfile.acapy
    ports:
      - 8080:8080
    env_file:
      - common.env
      - issuer.env
    entrypoint: [ "aca-py", "start", "--admin", "0.0.0.0", "8080", "--endpoint", "http://issuer:8000", "--inbound-transport", "http", "0.0.0.0", "8000"]
  holder:
    build:
      context: .
      dockerfile: Dockerfile.acapy
    ports:
      - 7070:7070
    env_file:
      - common.env
      - holder.env
    entrypoint: [ "aca-py", "start", "--admin", "0.0.0.0", "7070", "--endpoint", "http://holder:7000", "--inbound-transport", "http", "0.0.0.0", "7000"]


