###
# issuer create cred-offer with no connection
# @name cred_ex
POST {{issuerAdminUrl}}/issue-credential/create-offer
Content-Type: application/json

{
  "auto_issue": true,
  "auto_remove": false,
  "comment": "oob issuance test",
  "cred_def_id": "SXYE3iBSWrF8jh57m4yhga:3:CL:658408:default",
  "credential_preview": {
    "@type": "issue-credential/1.0/credential-preview",
    "attributes": [
      { "mime-type": "text/plain", "name": "name", "value": "Alice Smith" },
      { "mime-type": "text/plain", "name": "birthdate_dateint", "value": "19981007" },
      { "mime-type": "text/plain", "name": "degree", "value": "Maths" },
      { "mime-type": "text/plain", "name": "date", "value": "2018-05-28" },
      { "mime-type": "text/plain", "name": "timestamp", "value": "1665130918" }
    ]
  },
  "trace": false
}

###
@cred_ex_id = {{cred_ex.response.body.credential_exchange_id}}

###
# issuer create out-of-band invitation with cred-offer
# @name oob_invitation
POST {{issuerAdminUrl}}/out-of-band/create-invitation
Content-Type: application/json

{
  "alias": "This is transcript for Alice",
  "handshake_protocols": [
    "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/connections/1.0"
  ],
  "attachments": [
    {
      "id": "{{cred_ex_id}}",
      "type": "credential-offer"
    }
  ]
}

###
# holder receive out-of-band invitation from issuer.
POST {{holderAdminUrl}}/out-of-band/receive-invitation
Content-Type: application/json

{{oob_invitation.response.body.invitation}}

###
# @name credentials
GET {{holderAdminUrl}}/credentials
Content-Type: application/json