###
# setup schema
# @name schema
POST {{issuerAdminUrl}}/schemas
Content-Type: application/json

{
  "schema_name": "schema degree",
  "schema_version": "2023.01.18",
  "attributes": ["name","date","degree","birthdate_dateint","timestamp"]
}

###
# setup credDef
POST {{issuerAdminUrl}}/credential-definitions
Content-Type: application/json

{
  "schema_id": "SXYE3iBSWrF8jh57m4yhga:2:schema degree:2023.01.18",
  "support_revocation": false,
  "tag": "default"
}

###
# list schema
GET {{issuerAdminUrl}}/schemas/created
Content-Type: application/json

###
# list credDef
GET {{issuerAdminUrl}}/credential-definitions/created
Content-Type: application/json