###
# invitation 생성
# @name invitation
POST {{issuerAdminUrl}}/connections/create-invitation?alias=Faber&auto_accept=true&multi_use=false&public=false
Content-Type: application/json

{}

###
@invitation_connection_id = {{invitation.response.body.connection_id}}

###
# @name issue_credential_records
GET {{issuerAdminUrl}}/issue-credential/records?thread_id=5467630c-3118-4568-afb5-2e79dc4d4680
Content-Type: application/json

@cxid = {{issue_credential_records.response.body.results[0].credential_exchange_id}}

###
# delete issue-credential record
DELETE {{issuerAdminUrl}}/issue-credential/records/{{cxid}}

###
# @name present_proof_without_connection
POST {{issuerAdminUrl}}/present-proof/create-request
Content-Type: application/json

{
  "comment": "string",
  "proof_request": {
    "name": "Proof request",
    "nonce": "1",
    "requested_attributes": {
      "additionalProp1": {
        "names": [
          "name"
        ],
        "restrictions": [
          {
            "cred_def_id": "SXYE3iBSWrF8jh57m4yhga:3:CL:620394:2022.12.13"
          }
        ]
      }
    },
    "requested_predicates": {},
    "version": "1.0"
  }
}

###
@oob_px = {{present_proof_without_connection.response.body.presentation_exchange_id}}

###
# @name present_proof_records
GET {{issuerAdminUrl}}/present-proof/records

@pxid = {{present_proof_records.response.body.results[0].presentation_exchange_id}}

###
# delete present-proof record
DELETE {{issuerAdminUrl}}/present-proof/records/{{pxid}}

###
# create cred-offer without connection
# @name oob_cx
POST {{issuerAdminUrl}}/issue-credential/create-offer
Content-Type: application/json

{
  "auto_issue": true,
  "auto_remove": false,
  "comment": "oob issuance test",
  "cred_def_id": "SXYE3iBSWrF8jh57m4yhga:3:CL:620394:2022.12.13",
  "credential_preview": {
    "@type": "issue-credential/1.0/credential-preview",
    "attributes": [
      { "mime-type": "text/plain", "name": "name", "value": "Alice Smith" },
      { "mime-type": "text/plain", "name": "date", "value": "2018-05-28" },
      { "mime-type": "text/plain", "name": "degree", "value": "Maths" },
      { "mime-type": "text/plain", "name": "birthdate_dateint", "value": "19981007" },
      { "mime-type": "text/plain", "name": "timestamp", "value": "1665130918" }
    ]
  },
  "trace": false
}

###
@oob_cx_id = {{oob_cx.response.body.credential_exchange_id}}

###
# create out-of-band invitation with cred-offer
POST {{issuerAdminUrl}}/out-of-band/create-invitation
Content-Type: application/json

{
  "alias": "This is transcript for Alice",
  "attachments": [
    {
      "id": "{{oob_cx_id}}",
      "type": "credential-offer"
    }
  ],
  "handshake_protocols": [
    "https://didcomm.org/connections/1.0"
  ]
}

###
# create out-of-band invitation with present-proof
POST {{issuerAdminUrl}}/out-of-band/create-invitation
Content-Type: application/json

{
  "alias": "This is transcript presentation request",
  "attachments": [
    {
      "id": "{{oob_px}}",
      "type": "present-proof"
    }
  ]
}