###
# connection 조회
# @name connections
GET {{issuerAdminUrl}}/connections
Content-Type: application/json

###
# connection 삭제
DELETE {{issuerAdminUrl}}/connections/{{connections.response.body.results[0].connection_id}}
Content-Type: application/json

###
# @name issue_credential_records
GET {{issuerAdminUrl}}/issue-credential/records
Content-Type: application/json

###
# delete issue-credential record
DELETE {{issuerAdminUrl}}/issue-credential/records/{{issue_credential_records.response.body.results[0].credential_exchange_id}}

###
# connection 조회
# @name connections
GET {{holderAdminUrl}}/connections
Content-Type: application/json

###
# connection 삭제
DELETE {{holderAdminUrl}}/connections/{{connections.response.body.results[0].connection_id}}
Content-Type: application/json

###
# @name issue_credential_records
GET {{holderAdminUrl}}/issue-credential/records
Content-Type: application/json

###
# delete issue-credential record
DELETE {{holderAdminUrl}}/issue-credential/records/{{issue_credential_records.response.body.results[0].credential_exchange_id}}
