###
# setup schema
# @name schema
POST {{issuerAdminUrl}}/schemas
Content-Type: application/json

{
  "schema_name": "transacript",
  "schema_version": "23.01.26",
  "attributes": ["name","date","degree","birthdate_dateint","timestamp"]
}

###
# setup credDef
# @creddef
POST {{issuerAdminUrl}}/credential-definitions
Content-Type: application/json

{
  "schema_id": "{{schema.response.body.schema_id}}",
  "support_revocation": false,
  "tag": "4"
}

###
# list schema
GET {{issuerAdminUrl}}/schemas/created
Content-Type: application/json

###
# list credDef
GET {{issuerAdminUrl}}/credential-definitions/created
Content-Type: application/json