###
# schema 정의
POST {{baseUrl}}/schemas
Content-Type: application/json

{
  "schema_name": "schema degree",
  "schema_version": "2022.12.13",
  "attributes": ["name","date","degree","birthdate_dateint","timestamp"]
}

###
# schema 조회
GET {{baseUrl}}/schemas/created
Content-Type: application/json

###
# credDef 정의
POST {{baseUrl}}/credential-definitions
Content-Type: application/json

{
  "schema_id": "SXYE3iBSWrF8jh57m4yhga:2:schema degree:2022.12.13",
  "support_revocation": false,
  "tag": "2022.12.13"
}

###
# credDef 조회
GET {{baseUrl}}/credential-definitions/created
Content-Type: application/json

###
# connection 조회
GET {{baseUrl}}/connections
Content-Type: application/json

###
# connection 삭제
DELETE {{baseUrl}}/connections/c3b2f500-1756-412f-915b-d52c3875f0f8
Content-Type: application/json

###
# invitation 생성
POST {{baseUrl}}/connections/create-invitation?alias=Faber&auto_accept=true&multi_use=false&public=false
Content-Type: application/json

{}

###
# list issue-credential records
GET {{baseUrl}}/issue-credential/records
Content-Type: application/json

###
# delete issue-credential record
DELETE {{baseUrl}}/issue-credential/records/a2d41aa2-4036-4e04-a2b8-8fe3676bfedf

###
# create cred-offer without connection
POST {{baseUrl}}/issue-credential/create-offer
Content-Type: application/json

{
  "auto_issue": true,
  "auto_remove": false,
  "comment": "oob issuance test",
  "cred_def_id": "SXYE3iBSWrF8jh57m4yhga:3:CL:618924:2022.12.12",
  "credential_preview": {
    "@type": "issue-credential/1.0/credential-preview",
    "attributes": [
      {
        "mime-type": "text/plain",
        "name": "name",
        "value": "martini"
      },
      {
        "mime-type": "text/plain",
        "name": "score",
        "value": "4.9"
      }
    ]
  },
  "trace": false
}

###
# create out-of-band invitation with cred-offer
POST {{baseUrl}}/out-of-band/create-invitation
Content-Type: application/json

{
  "alias": "This is transcript for Alice",
  "attachments": [
    {
      "id": "4d75b7eb-a59d-4452-a15b-9ebea0375b36",
      "type": "credential-offer"
    }
  ],
  "handshake_protocols": [
    "https://didcomm.org/connections/1.0"
  ]
}