###
# schema 정의
POST {{baseUrl}}/schemas
Content-Type: application/json

{
  "schema_name": "schema degree",
  "schema_version": "2022.12.13",
  "attributes": ["name","date","degree","birthdate_dateint","timestamp"]
}

###
# schema 조회
GET {{baseUrl}}/schemas/created
Content-Type: application/json

###
# credDef 정의
POST {{baseUrl}}/credential-definitions
Content-Type: application/json

{
  "schema_id": "SXYE3iBSWrF8jh57m4yhga:2:schema degree:2022.12.13",
  "support_revocation": false,
  "tag": "2022.12.13"
}

###
# credDef 조회
GET {{baseUrl}}/credential-definitions/created
Content-Type: application/json

###
# connection 조회
GET {{baseUrl}}/connections
Content-Type: application/json

###
# connection 삭제
DELETE {{baseUrl}}/connections/112a0eb3-fe1c-4822-8e08-2cc26f0005ea
Content-Type: application/json

###
# invitation 생성
POST {{baseUrl}}/connections/create-invitation?alias=Faber&auto_accept=true&multi_use=false&public=false
Content-Type: application/json

{}

###
# list issue-credential records
GET {{baseUrl}}/issue-credential/records
Content-Type: application/json

###
# delete issue-credential record
DELETE {{baseUrl}}/issue-credential/records/c9aef1fe-59b9-4127-af80-318b4f2f12a6

###
# list present-proof records
GET {{baseUrl}}/present-proof/records

###
# delete present-proof record
DELETE {{baseUrl}}/present-proof/records/029624b0-c3a6-4fb9-8668-8ba434fd68ed

###
# create cred-offer without connection
POST {{baseUrl}}/issue-credential/create-offer
Content-Type: application/json

{
  "auto_issue": true,
  "auto_remove": false,
  "comment": "oob issuance test",
  "cred_def_id": "SXYE3iBSWrF8jh57m4yhga:3:CL:620394:2022.12.13",
  "credential_preview": {
    "@type": "issue-credential/1.0/credential-preview",
    "attributes": [
      { "mime-type": "text/plain", "name": "name", "value": "Alice Smith" },
      { "mime-type": "text/plain", "name": "date", "value": "2018-05-28" },
      { "mime-type": "text/plain", "name": "degree", "value": "Maths" },
      { "mime-type": "text/plain", "name": "birthdate_dateint", "value": "19981007" },
      { "mime-type": "text/plain", "name": "timestamp", "value": "1665130918" }
    ]
  },
  "trace": false
}

###
# create out-of-band invitation with cred-offer
POST {{baseUrl}}/out-of-band/create-invitation
Content-Type: application/json

{
  "alias": "This is transcript for Alice",
  "attachments": [
    {
      "id": "f5c515eb-c8e8-4034-9ee8-683e4cdec364",
      "type": "credential-offer"
    }
  ],
  "handshake_protocols": [
    "https://didcomm.org/connections/1.0"
  ]
}